### ISSUE TITLE
getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS.

### ISSUE THREAD

**Issue by wann2** [nakulkundaliya/ionic-3-video-calling-using-webrtc#6]
I've got the below error when I click CALL button.

getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS.

Could you help me to fix it?

**Comment by HybridEtpl** [comment]
Did you solve this issue?

**Comment by sergei202** [comment]
@HybridEtpl:  I finally got around the issue by installing `cordova-plugin-crosswalk-webview`.

Last issue to tackle is to get Ionic to request the camera privileges.
